// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdyMd73T17i5e0ubEZhB_44WAiYXVJLPA',
    appId: '1:44759652697:web:cf2ce19f185d790c811448',
    messagingSenderId: '44759652697',
    projectId: 'tiktokclone-3ca59',
    authDomain: 'tiktokclone-3ca59.firebaseapp.com',
    databaseURL: 'https://tiktokclone-3ca59-default-rtdb.firebaseio.com',
    storageBucket: 'tiktokclone-3ca59.appspot.com',
    measurementId: 'G-ZB7XGGB09H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8RswlzC_7uyiaF3idbJ6eTOhX0dWXHVU',
    appId: '1:44759652697:android:65e9c9c9d63f041c811448',
    messagingSenderId: '44759652697',
    projectId: 'tiktokclone-3ca59',
    databaseURL: 'https://tiktokclone-3ca59-default-rtdb.firebaseio.com',
    storageBucket: 'tiktokclone-3ca59.appspot.com',
  );
}
